<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Leo</string>
	<key>scopeName</key>
	<string>source.leo</string>
	<key>fileTypes</key>
	<array>
		<string>leo</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#function_declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_functions_call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import_file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#program_file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#program_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#integer_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#built-in_core_assign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#boolean_constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_public</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_private</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_record</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_let</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_then</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_mapping</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inside_braces</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type_params</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_parameters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#console_methods</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>address_literal</key>
		<dict>
			<key>comment</key>
			<string>Address</string>
			<key>match</key>
			<string>\baleo1[a-z0-9]*</string>
			<key>name</key>
			<string>address.literal.value.leo</string>
		</dict>
		<key>async_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.async.leo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.finalize.call.leo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Storage type async</string>
			<key>
