<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Leo</string>
	<key>scopeName</key>
	<string>source.leo</string>
	<key>fileTypes</key>
	<array>
		<string>leo</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#function_declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_functions_call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import_file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#program_file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#program_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#integer_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#built-in_core_assign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#boolean_constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_public</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_private</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_record</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_let</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_then</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_type_mapping</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inside_braces</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type_params</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_parameters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#console_methods</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>transition_name</key>
	        <dict>
	            <key>match</key>
	            <string>\btransition\s+(\w+)</string>
	            <key>captures</key>
	            <dict>
	                <key>1</key>
	                <dict>
	                    <key>name</key>
	                    <string>entity.name.transition.leo</string>
	                </dict>
	            </dict>
	        </dict>
		<key>address_literal</key>
		<dict>
			<key>comment</key>
			<string>Address</string>
			<key>match</key>
			<string>\baleo1[a-z0-9]*</string>
			<key>name</key>
			<string>address.literal.value.leo</string>
		</dict>
		<key>async_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.async.leo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.finalize.call.leo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Storage type async</string>
			<key>match</key>
			<string>\basync(?:\s+finalize\(\))?\b</string>
		</dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.begin.leo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.leo</string>
			<key>patterns</key>
			<array>
				<dict>
			            <key>include</key>
			            <string>#transition_name</string>
			        </dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.leo</string>
				</dict>
			</array>
		</dict>
		<key>boolean_constant</key>
		<dict>
			<key>match</key>
			<string>\b(?:true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.leo</string>
		</dict>
		<key>built-in_core_assign</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.leo</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?:include|import|use|const|let|mut|self|return)\b</string>
		</dict>
		<key>console_methods</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.console.log.leo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.console.assert.leo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Console methods</string>
			<key>match</key>
			<string>\b(?:console\.log|console\.assert)\b</string>
		</dict>
		<key>control_keyword</key>
		<dict>
			<key>comment</key>
			<string>Control keywords</string>
			<key>match</key>
			<string>\b(?:if|else|elif|for|while|loop|break|continue|match|in|where)\b</string>
			<key>name</key>
			<string>keyword.control.leo</string>
		</dict>
		<key>function_declaration</key>
		<dict>
			<key>begin</key>
			<string>\bfunction\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.declaration.leo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?={)</string>
			<key>name</key>
			<string>meta.function.declaration.leo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_parameters</string>
				</dict>
			</array>
		</dict>
		<key>function_parameters</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function.parameters.leo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\w+\b</string>
					<key>name</key>
					<string>variable.parameter.leo</string>
				</dict>
			</array>
		</dict>
		<key>import_file</key>
		<dict>
			<key>match</key>
			<string>import\s+\S+</string>
			<key>name</key>
			<string>keyword.control.import.leo</string>
		</dict>
		<key>import_keyword</key>
		<dict>
			<key>match</key>
			<string>\b(?:import|include|use)\b</string>
			<key>name</key>
			<string>keyword.control.import.leo</string>
		</dict>
		<key>inside_braces</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.block.braces.leo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_literal</string>
				</dict>
			</array>
		</dict>
		<key>integer_literal</key>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.leo</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.leo</string>
		</dict>
		<key>program_file</key>
		<dict>
			<key>comment</key>
			<string>Program file</string>
			<key>match</key>
			<string>\b(?:program\.leo)\b</string>
			<key>name</key>
			<string>source.file.program.leo</string>
		</dict>
		<key>string_literal</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.leo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.leo</string>
				</dict>
			</array>
		</dict>
		<key>type_keyword</key>
		<dict>
			<key>match</key>
			<string>\b(?:int|u8|u16|u32|u64|i8|i16|i32|i64|field|array|bool|string)\b</string>
			<key>name</key>
			<string>keyword.type.leo</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.leo</string>
</dict>
</plist>
